# 공통 설정: 모든 환경에서 공유

spring:
  application:
    name: olla-climbing
  servlet: # 이미지 크기 제한 
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    group:
      local:
        - local
        - secret
      prod:
        - prod
        - secret

      