# 🚨 절대 Git 커밋 금지. 서버에 별도로 보관하는 민감한 정보들입니다.

spring:
  datasource:
    # 서버 내부 DB 연결 후 교체 필요
    url: jdbc:mysql://localhost:3306/olla_db?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mail:
    host: smtp.gmail.com
    port: 587
    username: kwoo2618
    password: ppp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          timeout: 5000

jwt:
  secret: ppp

# coolsms:
#  api-key: "NCSVOL5ZMIJUGJ35"
#  api-secret: "6GTAKM0MGFY2W6QRYSWIN8IVFCAU6LUZ"
#  sender-number: "01029625832" # 하이픈(-) 없이 발신번호 숫자만 입력

google:
  sheet:
    id: "ppp"

file:
  upload-dir: "/home/ubuntu/olla-uploads/"

